steps:
- id: 'Deploy to Environment'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
    'deploy',
    'serve',
    '--entry-point',
    'serve',
    '--runtime',
    'python37',
    '--trigger-http',
    '--source',
    'cloud-functions/serve/'
    ]
